[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v -s

;testpaths = tests
;Pytest будет искать тесты в папке tests.
;
;python_files = test_*.py
;Файлы тестов должны начинаться с test_.

;python_functions = test_*
;Функции тестов должны начинаться с test_.
;
;addopts = -v -s
;Каждый запуск будет подробным и с выводом логов.